//
// Created by Shae Bolt on 12/16/2017.
//

#include "FileSystem.h"

#include "root_directory.h" // This is a configuration file generated by CMake.

namespace filesys {
    std::string const &getRoot() {
        return config::root_dir;
    }

    std::string getPathFromRoot(const std::string &path) {
        return getRoot() + std::string("/") + path;
    }

    std::string getPathFromBin(const std::string &path) {
        return "../" + path;
    }
}